version: "3.1"

services:
  db:
    image: mysql:8
    container_name: library-db-container
    network_mode: bridge
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: library
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    expose:
      - 3306
    ports:
      - 3306:3306
    volumes:
      - library_db:/var/lib/mysql

  library-app:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: bridge
    container_name: library-app-container
    depends_on:
      - db
    links:
      - db
    expose:
      - 8080
    ports:
      - 8080:8080

volumes:
  library_db: