server:
  error:
    include-stacktrace: on_trace_param

spring:
  datasource:
    url: jdbc:mysql://db:3306/library?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
#    testWhileIdle: true
#    hikari:
#      initialization-fail-timeout: 0
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: update
    show-sql: true

#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE

info:
  app: Library CRUD
  github: https://github.com/GustavoSaga/library